events {}

http {
    server {
        listen 80;

        location /chatrooms {
            proxy_pass http://chatroom-api:8082;
        }

        location /users {
            proxy_pass http://user-service:3000;
        }
    }
}
